// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  link_card: dynamic(() => import("./LinkCard")),
  page_header: dynamic(() => import("./PageHeader")),
};
